/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksFavoriteRouteImport } from './routes/books/favorite'
import { Route as BooksCreateRouteImport } from './routes/books/create'
import { Route as BooksBooksRouteImport } from './routes/books/books'
import { Route as BooksIdRouteImport } from './routes/books/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksFavoriteRoute = BooksFavoriteRouteImport.update({
  id: '/books/favorite',
  path: '/books/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksCreateRoute = BooksCreateRouteImport.update({
  id: '/books/create',
  path: '/books/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBooksRoute = BooksBooksRouteImport.update({
  id: '/books/books',
  path: '/books/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$id': typeof BooksIdRoute
  '/books/books': typeof BooksBooksRoute
  '/books/create': typeof BooksCreateRoute
  '/books/favorite': typeof BooksFavoriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$id': typeof BooksIdRoute
  '/books/books': typeof BooksBooksRoute
  '/books/create': typeof BooksCreateRoute
  '/books/favorite': typeof BooksFavoriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$id': typeof BooksIdRoute
  '/books/books': typeof BooksBooksRoute
  '/books/create': typeof BooksCreateRoute
  '/books/favorite': typeof BooksFavoriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/books/$id'
    | '/books/books'
    | '/books/create'
    | '/books/favorite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/books/$id'
    | '/books/books'
    | '/books/create'
    | '/books/favorite'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/books/$id'
    | '/books/books'
    | '/books/create'
    | '/books/favorite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BooksIdRoute: typeof BooksIdRoute
  BooksBooksRoute: typeof BooksBooksRoute
  BooksCreateRoute: typeof BooksCreateRoute
  BooksFavoriteRoute: typeof BooksFavoriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/favorite': {
      id: '/books/favorite'
      path: '/books/favorite'
      fullPath: '/books/favorite'
      preLoaderRoute: typeof BooksFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/create': {
      id: '/books/create'
      path: '/books/create'
      fullPath: '/books/create'
      preLoaderRoute: typeof BooksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/books': {
      id: '/books/books'
      path: '/books/books'
      fullPath: '/books/books'
      preLoaderRoute: typeof BooksBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BooksIdRoute: BooksIdRoute,
  BooksBooksRoute: BooksBooksRoute,
  BooksCreateRoute: BooksCreateRoute,
  BooksFavoriteRoute: BooksFavoriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
